DOMAIN = "skelly_queue"

CONF_ADDRESS = "address"
CONF_PLAY_CHAR = "play_char"
CONF_CMD_CHAR = "cmd_char"
CONF_MEDIA_DIR = "media_dir"
CONF_ALLOW_REMOTE = "allow_remote_urls"
CONF_CACHE_DIR = "cache_dir"
CONF_MAX_CACHE_MB = "max_cache_mb"

SERVICE_ENQUEUE = "enqueue"
SERVICE_ENQUEUE_URL = "enqueue_url"
SERVICE_ENQUEUE_M3U = "enqueue_m3u"
SERVICE_PLAY = "play"
SERVICE_SKIP = "skip"
SERVICE_CLEAR = "clear"
SERVICE_STOP = "stop"
