enqueue:
  name: Enqueue
  description: Add a local audio file (relative to media_dir) to the play queue
  fields:
    filename:
      required: true
      example: "boo_01.mp3"
      selector: { text: {} }

enqueue_url:
  name: Enqueue URL
  description: Download an http(s) audio file into cache and enqueue it
  fields:
    url:
      required: true
      example: "https://example.com/sounds/boo_01.mp3"
      selector: { text: {} }

enqueue_m3u:
  name: Enqueue M3U
  description: Download and parse a remote .m3u or .m3u8 and enqueue all playable entries
  fields:
    url:
      required: true
      example: "https://example.com/halloween_playlist.m3u8"
      selector: { text: {} }

enqueue_dir:
  name: Enqueue Directory
  description: Enqueue all playable files in a subfolder (relative to media_dir)
  fields:
    subpath:
      required: true
      example: "night_show"
      selector: { text: {} }
    recursive:
      required: false
      default: true
      selector: { boolean: {} }
    shuffle:
      required: false
      default: false
      selector: { boolean: {} }

enqueue_bulk:
  name: Enqueue Bulk
  description: Enqueue a list of filenames (relative to media_dir), in order
  fields:
    items:
      required: true
      example:
        - "boo_01.mp3"
        - "boo_02.mp3"
      selector:
        object: {}

play:
  name: Play
  description: Start or resume playback for the current queue

skip:
  name: Skip
  description: Skip to the next queued item

clear:
  name: Clear Queue
  description: Remove all items from the queue

stop:
  name: Stop
  description: Stop playback and clear the queue

